const territoryGroupedOptions = [
//    {
//     groupName: 'Worldwide one',
//     groupId: 'worldwide',
//     countries: [
//       { name: 'All Regions', id: 'all_regions', selected: false }
//     ]
//   },
  {
    groupName: 'Africa',
    groupId: 'africa',
    countries: [
      { name: 'Algeria', id: 'algeria', selected: false },
      { name: 'Angola', id: 'angola', selected: false },
      { name: 'Benin', id: 'benin', selected: false },
      { name: 'Botswana', id: 'botswana', selected: false },
      { name: 'Burkina Faso', id: 'burkina_faso', selected: false },
      { name: 'Burundi', id: 'burundi', selected: false },
      { name: 'Cabo Verde', id: 'cabo_verde', selected: false },
      { name: 'Cameroon', id: 'cameroon', selected: false },
      { name: 'Central African Republic', id: 'central_african_republic', selected: false },
      { name: 'Chad', id: 'chad', selected: false },
      { name: 'Comoros', id: 'comoros', selected: false },
      { name: 'Democratic Republic of the Congo', id: 'democratic_republic_of_the_congo', selected: false },
      { name: 'Republic of the Congo', id: 'republic_of_the_congo', selected: false },
      { name: "Côte d'Ivoire", id: 'cote_divoire', selected: false },
      { name: 'Djibouti', id: 'djibouti', selected: false },
      { name: 'Egypt', id: 'egypt', selected: false },
      { name: 'Equatorial Guinea', id: 'equatorial_guinea', selected: false },
      { name: 'Eritrea', id: 'eritrea', selected: false },
      { name: 'Eswatini', id: 'eswatini', selected: false },
      { name: 'Ethiopia', id: 'ethiopia', selected: false },
      { name: 'Gabon', id: 'gabon', selected: false },
      { name: 'Gambia', id: 'gambia', selected: false },
      { name: 'Ghana', id: 'ghana', selected: false },
      { name: 'Guinea', id: 'guinea', selected: false },
      { name: 'Guinea-Bissau', id: 'guinea_bissau', selected: false },
      { name: 'Kenya', id: 'kenya', selected: false },
      { name: 'Lesotho', id: 'lesotho', selected: false },
      { name: 'Liberia', id: 'liberia', selected: false },
      { name: 'Libya', id: 'libya', selected: false },
      { name: 'Madagascar', id: 'madagascar', selected: false },
      { name: 'Malawi', id: 'malawi', selected: false },
      { name: 'Mali', id: 'mali', selected: false },
      { name: 'Mauritania', id: 'mauritania', selected: false },
      { name: 'Mauritius', id: 'mauritius', selected: false },
      { name: 'Morocco', id: 'morocco', selected: false },
      { name: 'Mozambique', id: 'mozambique', selected: false },
      { name: 'Namibia', id: 'namibia', selected: false },
      { name: 'Niger', id: 'niger', selected: false },
      { name: 'Nigeria', id: 'nigeria', selected: false },
      { name: 'Rwanda', id: 'rwanda', selected: false },
      { name: 'São Tomé and Príncipe', id: 'sao_tome_and_principe', selected: false },
      { name: 'Senegal', id: 'senegal', selected: false },
      { name: 'Seychelles', id: 'seychelles', selected: false },
      { name: 'Sierra Leone', id: 'sierra_leone', selected: false },
      { name: 'Somalia', id: 'somalia', selected: false },
      { name: 'South Africa', id: 'south_africa', selected: false },
      { name: 'South Sudan', id: 'south_sudan', selected: false },
      { name: 'Sudan', id: 'sudan', selected: false },
      { name: 'Tanzania', id: 'tanzania', selected: false },
      { name: 'Togo', id: 'togo', selected: false },
      { name: 'Tunisia', id: 'tunisia', selected: false },
      { name: 'Uganda', id: 'uganda', selected: false },
      { name: 'Zambia', id: 'zambia', selected: false },
      { name: 'Zimbabwe', id: 'zimbabwe', selected: false }
    ]
  },
  {
    groupName: 'Asia',
    groupId: 'asia',
    countries: [
      { name: 'Afghanistan', id: 'afghanistan', selected: false },
      { name: 'Armenia', id: 'armenia', selected: false },
      { name: 'Azerbaijan', id: 'azerbaijan', selected: false },
      { name: 'Bahrain', id: 'bahrain', selected: false },
      { name: 'Bangladesh', id: 'bangladesh', selected: false },
      { name: 'Bhutan', id: 'bhutan', selected: false },
      { name: 'Brunei', id: 'brunei', selected: false },
      { name: 'Cambodia', id: 'cambodia', selected: false },
      { name: 'China', id: 'china', selected: false },
      { name: 'Georgia', id: 'georgia', selected: false },
      { name: 'Hong Kong', id: 'hong_kong', selected: false },
      { name: 'India', id: 'india', selected: false },
      { name: 'Indonesia', id: 'indonesia', selected: false },
      { name: 'Iran', id: 'iran', selected: false },
      { name: 'Iraq', id: 'iraq', selected: false },
      { name: 'Israel', id: 'israel', selected: false },
      { name: 'Japan', id: 'japan', selected: false },
      { name: 'Jordan', id: 'jordan', selected: false },
      { name: 'Kazakhstan', id: 'kazakhstan', selected: false },
      { name: 'Kuwait', id: 'kuwait', selected: false },
      { name: 'Kyrgyzstan', id: 'kyrgyzstan', selected: false },
      { name: 'Laos', id: 'laos', selected: false },
      { name: 'Lebanon', id: 'lebanon', selected: false },
      { name: 'Malaysia', id: 'malaysia', selected: false },
      { name: 'Maldives', id: 'maldives', selected: false },
      { name: 'Mongolia', id: 'mongolia', selected: false },
      { name: 'Myanmar', id: 'myanmar', selected: false },
      { name: 'Nepal', id: 'nepal', selected: false },
      { name: 'North Korea', id: 'north_korea', selected: false },
      { name: 'Oman', id: 'oman', selected: false },
      { name: 'Pakistan', id: 'pakistan', selected: false },
      { name: 'Palestine', id: 'palestine', selected: false },
      { name: 'Philippines', id: 'philippines', selected: false },
      { name: 'Qatar', id: 'qatar', selected: false },
      { name: 'Saudi Arabia', id: 'saudi_arabia', selected: false },
      { name: 'Singapore', id: 'singapore', selected: false },
      { name: 'South Korea', id: 'south_korea', selected: false },
      { name: 'Sri Lanka', id: 'sri_lanka', selected: false },
      { name: 'Syria', id: 'syria', selected: false },
      { name: 'Taiwan', id: 'taiwan', selected: false },
      { name: 'Tajikistan', id: 'tajikistan', selected: false },
      { name: 'Thailand', id: 'thailand', selected: false },
      { name: 'Timor-Leste', id: 'timor_leste', selected: false },
      { name: 'Turkey', id: 'turkey', selected: false },
      { name: 'Turkmenistan', id: 'turkmenistan', selected: false },
      { name: 'United Arab Emirates', id: 'united_arab_emirates', selected: false },
      { name: 'Uzbekistan', id: 'uzbekistan', selected: false },
      { name: 'Vietnam', id: 'vietnam', selected: false },
      { name: 'Yemen', id: 'yemen', selected: false }
    ]
  },
  {
    groupName: 'Europe',
    groupId: 'europe',
    countries: [
      { name: 'Albania', id: 'albania', selected: false },
      { name: 'Andorra', id: 'andorra', selected: false },
      { name: 'Austria', id: 'austria', selected: false },
      { name: 'Belarus', id: 'belarus', selected: false },
      { name: 'Belgium', id: 'belgium', selected: false },
      { name: 'Bosnia and Herzegovina', id: 'bosnia_and_herzegovina', selected: false },
      { name: 'Bulgaria', id: 'bulgaria', selected: false },
      { name: 'Croatia', id: 'croatia', selected: false },
      { name: 'Cyprus', id: 'cyprus', selected: false },
      { name: 'Czech Republic', id: 'czech_republic', selected: false },
      { name: 'Denmark', id: 'denmark', selected: false },
      { name: 'Estonia', id: 'estonia', selected: false },
      { name: 'Finland', id: 'finland', selected: false },
      { name: 'France', id: 'france', selected: false },
      { name: 'Germany', id: 'germany', selected: false },
      { name: 'Greece', id: 'greece', selected: false },
      { name: 'Hungary', id: 'hungary', selected: false },
      { name: 'Iceland', id: 'iceland', selected: false },
      { name: 'Ireland', id: 'ireland', selected: false },
      { name: 'Italy', id: 'italy', selected: false },
      { name: 'Kosovo', id: 'kosovo', selected: false },
      { name: 'Latvia', id: 'latvia', selected: false },
      { name: 'Liechtenstein', id: 'liechtenstein', selected: false },
      { name: 'Lithuania', id: 'lithuania', selected: false },
      { name: 'Luxembourg', id: 'luxembourg', selected: false },
      { name: 'Malta', id: 'malta', selected: false },
      { name: 'Moldova', id: 'moldova', selected: false },
      { name: 'Monaco', id: 'monaco', selected: false },
      { name: 'Montenegro', id: 'montenegro', selected: false },
      { name: 'Netherlands', id: 'netherlands', selected: false },
      { name: 'North Macedonia', id: 'north_macedonia', selected: false },
      { name: 'Norway', id: 'norway', selected: false },
      { name: 'Poland', id: 'poland', selected: false },
      { name: 'Portugal', id: 'portugal', selected: false },
      { name: 'Romania', id: 'romania', selected: false },
      { name: 'Russia', id: 'russia', selected: false },
      { name: 'San Marino', id: 'san_marino', selected: false },
      { name: 'Serbia', id: 'serbia', selected: false },
      { name: 'Slovakia', id: 'slovakia', selected: false },
      { name: 'Slovenia', id: 'slovenia', selected: false },
      { name: 'Spain', id: 'spain', selected: false },
      { name: 'Sweden', id: 'sweden', selected: false },
      { name: 'Switzerland', id: 'switzerland', selected: false },
      { name: 'Ukraine', id: 'ukraine', selected: false },
      { name: 'United Kingdom', id: 'united_kingdom', selected: false }
    ]
  },
  {
    groupName: 'Latin America & Caribbean',
    groupId: 'latam',
    countries: [
      { name: 'Argentina', id: 'argentina', selected: false },
      { name: 'Bahamas', id: 'bahamas', selected: false },
      { name: 'Barbados', id: 'barbados', selected: false },
      { name: 'Belize', id: 'belize', selected: false },
      { name: 'Bolivia', id: 'bolivia', selected: false },
      { name: 'Brazil', id: 'brazil', selected: false },
      { name: 'Chile', id: 'chile', selected: false },
      { name: 'Colombia', id: 'colombia', selected: false },
      { name: 'Costa Rica', id: 'costa_rica', selected: false },
      { name: 'Cuba', id: 'cuba', selected: false },
      { name: 'Dominica', id: 'dominica', selected: false },
      { name: 'Dominican Republic', id: 'dominican_republic', selected: false },
      { name: 'Ecuador', id: 'ecuador', selected: false },
      { name: 'El Salvador', id: 'el_salvador', selected: false },
      { name: 'Guatemala', id: 'guatemala', selected: false },
      { name: 'Guyana', id: 'guyana', selected: false },
      { name: 'Haiti', id: 'haiti', selected: false },
      { name: 'Honduras', id: 'honduras', selected: false },
      { name: 'Jamaica', id: 'jamaica', selected: false },
      { name: 'Mexico', id: 'mexico', selected: false },
      { name: 'Nicaragua', id: 'nicaragua', selected: false },
      { name: 'Panama', id: 'panama', selected: false },
      { name: 'Paraguay', id: 'paraguay', selected: false },
      { name: 'Peru', id: 'peru', selected: false },
      { name: 'Puerto Rico', id: 'puerto_rico', selected: false },
      { name: 'Trinidad and Tobago', id: 'trinidad_and_tobago', selected: false },
      { name: 'Uruguay', id: 'uruguay', selected: false },
      { name: 'Venezuela', id: 'venezuela', selected: false }
    ]
  },
  {
    groupName: 'North America',
    groupId: 'north_america',
    countries: [
      { name: 'Canada', id: 'canada', selected: false },
      { name: 'United States', id: 'united_states', selected: false },
      { name: 'Mexico', id: 'mexico', selected: false }
    ]
  },
  {
    groupName: 'Oceania',
    groupId: 'oceania',
    countries: [
      { name: 'Australia', id: 'australia', selected: false },
      { name: 'Fiji', id: 'fiji', selected: false },
      { name: 'Kiribati', id: 'kiribati', selected: false },
      { name: 'Marshall Islands', id: 'marshall_islands', selected: false },
      { name: 'Micronesia', id: 'micronesia', selected: false },
      { name: 'Nauru', id: 'nauru', selected: false },
      { name: 'New Zealand', id: 'new_zealand', selected: false },
      { name: 'Palau', id: 'palau', selected: false },
      { name: 'Papua New Guinea', id: 'papua_new_guinea', selected: false },
      { name: 'Samoa', id: 'samoa', selected: false },
      { name: 'Solomon Islands', id: 'solomon_islands', selected: false },
      { name: 'Tonga', id: 'tonga', selected: false },
      { name: 'Tuvalu', id: 'tuvalu', selected: false },
      { name: 'Vanuatu', id: 'vanuatu', selected: false }
    ]
  }
];
export default territoryGroupedOptions;
